### ISSUE TITLE
How could i get a account`s tx history from here or ethereumj

### ISSUE THREAD

**Issue by PhoenixZeng** [ether-camp/ethereum-harmony#108]
eg: like this https://etherscan.io/address/0x94c921fc2810335fb077ccfb745cff5e72d47572 ?

**Comment by zilm13** [comment]
@PhoenixZeng to have such type of history you should add listener with `ethereum.addListener()`, parse appropriate txes and save data in separate db

**Comment by PhoenixZeng** [comment]
well.
