### ISSUE TITLE
Let user know when contract, deployed via Harmony, failed to create because error in contructor

### ISSUE THREAD

**Issue by cupuyc** [ether-camp/ethereum-harmony#19]
Default contract deployed from Ethereum Studio may have error in constructor. It will not be created successfully.
We can let user know via few ways:
1. Keeping database of contracts deployed via Harmony and there vmtrace (or only errors in vmtrace).
2. Ethereum Studio should monitor transaction via ethereumJ JSON-RPC method `ethj_getTransactionReceipt`, which is also return more informative errors.

@asinyagin Please put your input

**Comment by asinyagin** [comment]
It would be great if Studio could get transaction errors in receipts. In the sandbox I've added a custom JSON RPC call which returns a receipt with a field `exception` https://github.com/ether-camp/ethereum-sandbox/blob/master/ethereum/receipt.js#L42. I think we can add something like it to ethereumj.

Does ethereumj have some custom JSON RPC calls?

**Comment by asinyagin** [comment]
Also, the custom receipt in the sandbox has `returnValue`.

**Comment by cupuyc** [comment]
@asinyagin 
Right, there is `ethj_getTransactionReceipt` (**ethj_** instead of eth_)
It has *error* field. Sample output is:
```
node> ethj_getTransactionReceipt 0x9fd06927abe517df70b59f92ba040a88b1117dd0f677b50a5032b9913a33c19d
{
  "transactionHash": "0x9fd06927abe517df70b59f92ba040a88b1117dd0f677b50a5032b9913a33c19d",
  "transactionIndex": "0x0",
  "blockHash": "0x2c0935452a8e943c0b8b9309ab866c8a94a6f6962ebb7d1f9a4f2418af529537",
  "blockNumber": "0x18733",
  "cumulativeGasUsed": "0x09965e",
  "gasUsed": "0x09965e",
  "contractAddress": "0xd5c1acbe590c64bd732ebe3513675371481d9bd0",
  "logs": [],
  "returnData": "0x",
  "error": "Operation with pc isn't 'JUMPDEST': PC[0];"
}
```

**Comment by asinyagin** [comment]
@cupuyc cool, I'll add the check to Studio.
