### ISSUE TITLE
OutOfMemory when runPrivate

### ISSUE THREAD

**Issue by adridadou** [ether-camp/ethereum-harmony#21]
I get an OutOfMemory when I run ./gradlew runPrivate while generating the dag file

I've removed a JavaArgs "-Xmx1G" and I don't have the error anymore

My env is OSX and my JVM version is 1.8.0_111

**Comment by cupuyc** [comment]
Thank you for pointing. I reverted to previous value `-Xmx3500M`. 
Excluding mining, Harmony must work well with 1GB.
