### ISSUE TITLE
Contract's event not working

### ISSUE THREAD

**Issue by dsapaev** [ether-camp/ethereum-harmony#22]
I have a contract 
[contract_bytecode.txt](https://github.com/ether-camp/ethereum-harmony/files/766552/contract_bytecode.txt)
and two independent ethereum clients for experiments. One of them is geth (deployed at 172.17.0.2 in the local net), second is harmony (deployed at 172.17.0.3). 

Contract address is 0xfad862e3c688455f25446904d06cda82d4386d88

I'm trying to execute my test script:
```
#!/bin/bash

host=$1

if [ "$host" == "http://172.17.0.2:8080" ]
then
    sb1=(-36)
    sb2=34
else
    sb1=(-6)
    sb2=4
fi


transaction="$(curl -X POST --data '{"jsonrpc":"2.0", "method":"eth_sendTransaction", "params":[{"from":"0x2644116ef02ee27563a8478052f5ff00ad6d24ad","gas":"0xf4240","to":"0xfad862e3c688455f25446904d06cda82d4386d88","data":"0xa6bc6395b294b4d6570e720da205d9589cdebbd9d185dbeff8a96532df8dbbc96b4aa505000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe403020000000000000000000000000000000000000000000000000000000000000000"}],"id":1}' $host)"
echo "transaction answer is $transaction"

filter="$(curl -X POST --data "{\"jsonrpc\":\"2.0\", \"method\":\"eth_newFilter\", \"params\":[{\"topics\":[],\"address\":\"0xfad862e3c688455f25446904d06cda82d4386d88\"}],\"id\":2}" $host)"
echo "filter answer is $filter"


flogs="$(curl -X POST --data "{\"jsonrpc\":\"2.0\", \"method\":\"eth_getFilterLogs\", \"params\":[\"${filter:($sb1):$sb2}\"], \"id\":3}" $host)"
echo "flogs answer is $flogs"

again=0
while [ "$again" -lt "60" ]
do
    fchanges="$(curl -X POST --data "{\"jsonrpc\":\"2.0\", \"method\":\"eth_getFilterChanges\", \"params\":[\"${filter:($sb1):$sb2}\"], \"id\":4}" $host)"
    echo "fchanges answer is $fchanges"
    again=${#fchanges}.
    sleep 2s
done
```

So, if i run ./testJava.sh "http://172.17.0.2:8080", i getting the right result after some time of the loop execution:

fchanges answer is {"jsonrpc":"2.0","id":4,"result":[]}
...
fchanges answer is {"jsonrpc":"2.0","id":4,"result":[{"address":"0xfad862e3c688455f25446904d06cda82d4386d88","topics":["0x86d78d4604d1118b84159ec7d58eb191e7b46f989379253d3f3516022c0a93b6"],"data":"0x0000000000000000000000002644116ef02ee27563a8478052f5ff00ad6d24ad0000000000000000000000000000000000000000000000000000000000000001b294b4d6570e720da205d9589cdebbd9d185dbeff8a96532df8dbbc96b4aa505000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe403020000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0xb2e5","transactionIndex":"0x0","transactionHash":"0x067566de3baf4f8e86c8da7fbc2b56b1c8e9dfb102350868d3d2f86b970d59f8","blockHash":"0xa6d3215abb9b6a50dab22647dce69ff45c670476aefc27bb2dfb5e39f6a05369","logIndex":"0x0","removed":false}]}

But when i run ./testJava.sh "http://172.17.0.3:8080/rpc", i always getting empty result

fchanges answer is {"jsonrpc":"2.0","id":4,"result":[]}

So, i can't catch contract events

Maybe i did something wrong?

**Comment by dsapaev** [comment]
[contract_interface.txt](https://github.com/ether-camp/ethereum-harmony/files/773550/contract_interface.txt)

**Comment by cupuyc** [comment]
Fixed by https://github.com/ether-camp/ethereum-harmony/commit/81e8ec91641546326b88e5863129ce6eb9b77b20
