### ISSUE TITLE
Wallet doesn't update amount in Private Miner mode

### ISSUE THREAD

**Issue by ranjan008** [ether-camp/ethereum-harmony#23]
In harmony by UI if i send a transaction then it is being highlighted but when i am trying to send the transaction usi JSON-RPC from the console the transaction is going through but the transaction is not being highlighted.

Also I tried to implement the Keystore functionality of harmony in my own project by just copying the com.ether.camp.harmony.keystore package in my project then only the transactions from the address specified in the genesis block is going through but the transactions generated using the keystore is being submitted successfully to the network but it is not being mined.

**Comment by cupuyc** [comment]
@ranjan008 What do you mean by "highlighted transaction"?

Please try `./gradlew runPrivate` to run private miner. Ensure block counter does increase over time. Let me know if sending transactions works in that case.

If you have custom private network - I would need info about it.

**Comment by ranjan008** [comment]
I have tried the way you mentioned and block counter does increase over time but sending transaction using JSON-RPC in rpcusage through command prompt is not increasing the address ether amount and also the no of transactions is always 0.

And for my other project i am using private network but it is similar to the ethereumj config file because in that I have implemented ethereumj 1.4.1 along with the keystore functionality of harmony.

**Comment by cupuyc** [comment]
I see. 

We have a cute method for checking what is wrong with a transaction. After you sent transaction, please call JSON-RPC method `ethj_getTransactionReceipt txHash` and pass transaction hash. It is convenient to do that via Harmony Terminal at http://localhost:8080/terminal
Please post the resulted receipt here. It may show errors.

**Comment by ranjan008** [comment]
eth_getTransactionReceipt 0x728b4a55d01d5c077516815e5f4fcf20dffa2e66de26b2d1bddf7cb7409caea7
{
  "transactionHash": "0x728b4a55d01d5c077516815e5f4fcf20dffa2e66de26b2d1bddf7cb7409caea7",
  "transactionIndex": "0x0",
  "blockHash": "0x2c352edd7176f7699d5cfc129e6df9f9e7c892d909e287d8edb06d4d6613737b",
  "blockNumber": "0x7cd",
  "cumulativeGasUsed": "0x5208",
  "gasUsed": "0x5208",
  "contractAddress": null,
  "logs": []
}

this is the result i am getting after querying for transaction receipt.
but the wallet amounts are not changing

**Comment by cupuyc** [comment]
@ranjan008 Sorry, I didn't emphasize that our  `ethj_getTransactionReceipt` is different from `eth_getTransactionReceipt` by one extra **J** letter in **ethj**.

Please check again.

**Comment by ranjan008** [comment]
@cupuyc  i didn't meant that i have used the harmony terminal only and there the method name is showing eth_getTransactionReceipt only and the result which i pasted is what i got in harmony terminal.

**Comment by cupuyc** [comment]
@ranjan008 from you previous receipt I can see that transaction was included in block = means was processed by miner and included in blockchain.

What is your expected output from performing transaction?

Note: with **ethj_getTransactionReceipt** one can find out if there were errors executing contract code.

**Comment by ranjan008** [comment]
I am really sorry for my foolishness I was not aware about this method and used the traditional one really sorry and i got below result after executing this method
{
  "transactionHash": "0x728b4a55d01d5c077516815e5f4fcf20dffa2e66de26b2d1bddf7cb7409caea7",
  "transactionIndex": "0x0",
  "blockHash": "0x2c352edd7176f7699d5cfc129e6df9f9e7c892d909e287d8edb06d4d6613737b",
  "blockNumber": "0x7cd",
  "cumulativeGasUsed": "0x5208",
  "gasUsed": "0x5208",
  "contractAddress": null,
  "logs": [],
  "returnData": "0x",
  "error": ""
}

**Comment by cupuyc** [comment]
So transaction went correctly.

Let's back to my original question: _What do you mean by "highlighted transaction"?_
How do you monitor transaction? Feel free to send screenshort.

**Comment by cupuyc** [comment]
Issues:
 - in Private Miner - sending amount in wallet doesn't update wallet automatically when transaction is applied;
 - possibly same in other network when tx was processed outside of wallet (with json-rpc).

**Comment by cupuyc** [comment]
Fixed with https://github.com/ether-camp/ethereum-harmony/commit/dc82dae36300913b12c04bcdeb63d2519755e8e9
