### ISSUE TITLE
Instance doesn't stop immediatelly after _Ctrl+C_ on Mac.

### ISSUE THREAD

**Issue by cupuyc** [ether-camp/ethereum-harmony#28]
Observed often on Mac when run via `./gradlew runRopsten` or via IDE.
Closing via _Ctrl+C_ shows that instance has been stopped, but process remains active and occupies DB LOCK file.

TODO check sample in EthereumJ-core first.

**Comment by cupuyc** [comment]
I've switched from gradle 2.3 to 3.4 and now command prompt waits for app to exit ~5-20 seconds.

@Nashatyrev What do you think? Is such long time is acceptable? Can we do anything more here?

**Comment by Nashatyrev** [comment]
Can you plz file an issue for core project?
