### ISSUE TITLE
Can't install Harmony 2.1.56 and 2.1.57 - could not create nul.json

### ISSUE THREAD

**Issue by kariezavr** [ether-camp/ethereum-harmony#39]
I'm not sure this Harmony problem, but I can't install 2.1.56 and 2.1.57 version. In both cases installation was stopped with message "c:\Program Files\EthereumHarmony\classes\static\bower_components\datamaps\src\js\data\nul.json Could not create this file. Shall I try again?" (yes/cancel).
Windows 10 64bit

**Comment by mkalinin** [comment]
Fixed in https://github.com/ether-camp/ethereum-harmony/commit/84408845856b9dbc420d34ed3239ea423a7e729c
New release is published: https://github.com/ether-camp/ethereum-harmony/releases/tag/v2.1b58

**Comment by mkalinin** [comment]
@kariezavr pls, check that new installer works

**Comment by kariezavr** [comment]
Thank's a lot! Works great!
