### ISSUE TITLE
RPC URL Breaks Compatibility - Separate RPC Port - MyEtherWallet

### ISSUE THREAD

**Issue by MysticRyuujin** [ether-camp/ethereum-harmony#41]
All other client implementations have the RPC port on 8545 and it is a direct interface to the JSON RPC API.

Tools such as MyEtherWallet expect the RPC to be separate from the web interface...but Harmony requires "/rpc" to be appended to the URL. That makes in impossible to use with MEW without customization. It makes it harder for developers to support EthereumJ nodes running via Harmony.

Would it not be easier to just expose 8545 directly to the running EthereumJ node? Or perhaps expose it in addition to the /rpc URL?

**Comment by MysticRyuujin** [comment]
So MyCrypto has fixed this issue in their beta by allowing any URL path, I think it's still a nice to have, putting the RPC on the root of 8545 like the other clients, but I suppose it can be worked around via NGINX or something too...

**Comment by zilm13** [comment]
@MysticRyuujin it should work both on root and `/rpc`, you just need to set port to 8545
It's a command I run successfully on our server:
```
ubuntu@ethereumj-node01:~$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_protocolVersion","params":[],"id":67}' localhost:8080
{"jsonrpc":"2.0","id":67,"result":"63"}
```

**Comment by MysticRyuujin** [comment]
Awesome that the root works, and MyCrypto fixed this issue in their beta as well, allowing any URI

**Comment by Hackertalkz** [comment]
I am confused with something.

Crypto tipsActivate Plugin to receive tips in differenct cryptocurrenies - dealing with wordpress:  requires an RPC URL.  If I activate the plugin, I get an error message:
Go to crypto tips settings and configure the rpc url for your cryptocurrency wallet. A wallet with rpc set up is a must to use this plugin.

I have to deactivate the plugin just to work on my site.  Is the RPC URL the same address going to your Ethereum wallet address or Bitcoin address to send & recieve cryptos? Or is the RPC URL something else?

Please help me with this asap!
-- | --

**Comment by zilm13** [comment]
RPC url is http://localhost:8080
You could change it by passing variable `local.server.port`
