### ISSUE TITLE
Private key generation from insecure random mnemonic phrases.

### ISSUE THREAD

**Issue by juli** [ether-camp/ethereum-harmony#52]
Ethereum Harmony generates private keys using weak PRNGs functions (Java's java.util.random and Javascript's Math.random)
Funds sent to wallets generated using Ethereum Harmony could be at risk.

**Comment by zilm13** [comment]
@juli 
I've checked the code:
- private key generation uses `SecureRandom` inside default `ECKey` implementation so it's not affected. Also in `Account` class exists not secure constructor which is not used by anyone. To avoid mistakes in the future, it was modified to use SecureRandom.
- Mnemonic phrase generation uses PRNG both on backend and frontend. It shouldn't affect entropy, because it's less secure by idea and doesn't require 256 random bits.  So, you have less variance than in private key but it's comparable to 20+ symbol passwords with special characters (but if you are going to brute it, it would be more difficult than brute such passwords) and could be restored from your own memory (man memory!) which could be more important for some cases. Anyway I've changed PRNG to RNG in it and increased entropy a little. Also #53 was created. This issue is not critical when you run node locally (most common Harmony use case), but it's better to fix it with next release.

Overall I think we are not going to do bugfix release, because private key generation was not affected, but anyway your attention to our code helps us to make the Harmony better, so we will mention you in release notes of upcoming version.

**Comment by juli** [comment]
The passphrase generated using weak PRNG functions is used as a Ethereum private key, not as an encryption passphrase for a key generated in a secure way. You estimate it is equivalent to 122 bits security but it is dangerously less than that based on the following code and the bit length of the seeds of the PRNG functions being used. 

Ethereum Harmony Javascript UI code generates Ethereum address from a passphrase here:

https://github.com/ether-camp/ethereum-harmony/blob/29398ac6cde418e57d7078b16fdfe51fab4fdbd5/src/main/resources/static/js/app/popups.controller.js#L310-L312

The passphrase is generated using 5 words from the RPC service ([java.util.Random](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/util/Random.java#L89-L102), ~64 bits seed) and 1 extra word generated with Javascript using Math.random:

https://github.com/ether-camp/ethereum-harmony/blob/29398ac6cde418e57d7078b16fdfe51fab4fdbd5/src/main/resources/static/js/app/popups.controller.js#L324-L333

The Javascript code inserts an extra word at a random position as an attempt to improve the passphrase generated by the Java service?

The code to generate the extra word is the following:
https://github.com/ether-camp/ethereum-harmony/blob/1c1a158b9049c0dca0f683697a0bafde52ce38db/src/main/resources/static/js/app/util/generateWord.js#L4-L22

The way `Math.random` is used in `generateWord.js`  reduces the effort for an exhaustive search attack to less than 30 bits even if the web browser sets a stronger seed.

See:
"Make no mistake however: even though xorshift128+ is a huge improvement over MWC1616, it still is not cryptographically secure..."
from: https://v8project.blogspot.com.ar/2015/12/theres-mathrandom-and-then-theres.html

"Instances of java.util.Random are not cryptographically secure. Consider instead using SecureRandom ..."
from: https://docs.oracle.com/javase/7/docs/api/java/util/Random.html

**Comment by zilm13** [comment]
First of all, if you have read my reply, you should notice that I've changed all usages of PRNG to RNG both on frontend and backend.

The second
Let's estimate randomness of mnemonic phrase:
200k^5 (assuming 200k dict)
pseudo-word: 10^9 variations
none of them alone needs more than 32 bits of randomness, so the only issue with current solution is Pseudo-, not the seed length

so for the full mnemonic phrase: 200k^5*10^9 = 3.2e+35, it's about 2^118, 118bits

Tell me where I'm wrong

**Comment by dchest** [comment]
@zilm13 You can't assume that calling a non-cryptographically secure random number generator, even multiple times, will add entropy to the result, so your calculations are meaningless.

**Comment by juli** [comment]
Analyzing if exhaustive search of mnemonic private keys was practical is important to evaluate if users should be alerted and move their funds to new wallets, even if the patch is correct.
You have calculated the length in bits of the number you want to obtain but you are using a N sided dice to generate that number, where N is the number of possible values for the PRNG seed. 
If you seed a PRNG with 32 bits, then you are going to generate at most 2^32 different keys of 118bits.
The seed of `java.util.Random` is `System.nanoTime())`

**Comment by zilm13** [comment]
@dchest yeah, PRNG does not guarantee it

**Comment by zilm13** [comment]
@juli there is no difference how do you chose one of 200k words, with 2^32 or with 2^64, because both are greater, but @dchest is right that due to pseudo we are not guaranteed with 32 bits on every call.

**Comment by zilm13** [comment]
@juli @dchest we will make release after checking that the issue is correctly fixed.

**Comment by dchest** [comment]
@zilm13 that's basically what @juli is explaining — if the seed has 32 bits of entropy and the output of PRNG is a function of this seed, any transformation of it (including multiple calls) cannot not give you more than 32 bits of entropy.

**Comment by zilm13** [comment]
@dchest how much entropy has 64 bit key made from two 32-bit random keys assuming it used non PRNG random generator?

**Comment by dchest** [comment]
@zilm13 64 bits, if two 32-bit keys are chosen independently at random and each contain 32 bits of entropy.

**Comment by zilm13** [comment]
@dchest 
yeah we couldn't count PRNG as truly 32 bits in that case, you are right.
Changes are already in PR (based on window.crypto and SecureRandom), another developer will check it and we are going to release it soon.

**Comment by zilm13** [comment]
@juli We have released version with fixes and notified users in our gitter channel:
https://github.com/ether-camp/ethereum-harmony/releases/tag/v2.1b61
Thank you for reporting!
