### ISSUE TITLE
Issue compiling with IntelliJ (Lombok plugin)

### ISSUE THREAD

**Issue by ajlopez** [ether-camp/ethereum-harmony#55]
I had an issue compiling with IntelliJ. The first time, it didn't work "log variable undefined". Gradle command line build, worked.

Then I found that the Lombok plugin should be installed, and the annotation processing should be enabled.

Could you add the solution to README?

**Comment by zilm13** [comment]
@ajlopez Could you write it with fresh view, something like
For Intellij IDEA enable following settings:
- x
- x

**Comment by zilm13** [comment]
@ajlopez I've added wiki page for this
https://github.com/ether-camp/ethereum-harmony/wiki/Development-troubleshooting
