### ISSUE TITLE
Does the newest ethereumj-core-1.7.0-SNAPSHOT.jar include error?

### ISSUE THREAD

**Issue by lxiaodao** [ether-camp/ethereum-harmony#63]
1.Today ,when i run `gradlew runMain -Dserver.port=7000`,there is build error info:
```
E:\business\ethereum-harmony\src\main\java\com\ethercamp\harmony\jsonrpc\EthJson
RpcImpl.java:834: 错误: contracts可以在CompilationResult中访问private
        org.ethereum.solidity.compiler.CompilationResult.ContractMetadata contra
ctMetadata = result.contracts.values().iterator().next();
```
But this error is not exist yesterday,and i find the gradle download a new ethereumj-core-1.7.0-SNAPSHOT.jar.
So i think there is a bug in newest ethereumj-core-1.7.0-SNAPSHOT.jar

**Comment by zilm13** [comment]
Looks like we need to update Harmony too. Will push update.

**Comment by zilm13** [comment]
@lxiaodao should be fixed now!
Thank you for contacting us. We have change interface in ethereumj a bit and forget to change its usage in Harmony.

**Comment by lxiaodao** [comment]
@zilm13 I will try late,you are welcome.
