### ISSUE TITLE
Free space:is not correct.

### ISSUE THREAD

**Issue by orchome** [ether-camp/ethereum-harmony#67]
I have modified the storage directory,But the page display is wrong.

```
database.dir=/data/ethereumj/${database.name}
ethash.dir=/data/ethereumj/ethash
```

**Comment by mkalinin** [comment]
Basically, the problem occurs when database folder is located on the other drive than the system is.
These screens should shed a light on the problem:
![](https://files.gitter.im/orchome/9Ysa/00249EE2-B8E5-4B04-B413-6AD453407E96.png)
![](https://files.gitter.im/orchome/C356/FA0192B1-9A4A-4A8A-BAA6-2D6B37761877.png)
![](https://files.gitter.im/orchome/Ub5J/F8BC5BD5-3E4E-4C29-8247-02781129A1B1.png)

**Comment by zilm13** [comment]
@orchome @mkalinin 
Should be fixed with https://github.com/ether-camp/ethereum-harmony/commit/77a6c067b7284d8db8c09a7f33291c5e968fa306
but I don't have Windows system to test it, only Mac/Linux. Could you help?

**Comment by zilm13** [comment]
Ok, I'm closing this, if the bug appears on Windows, someone would probably create an issue.
