### ISSUE TITLE
Consfusing Memory used in Machine Info

### ISSUE THREAD

**Issue by mkalinin** [ether-camp/ethereum-harmony#71]
It might seem that `Memory used` shows memory used by Harmony instance, not by OS

**Comment by zilm13** [comment]
@mkalinin Always correct for me. How to reproduce your behaviour?
<img width="166" alt="screen shot 2018-04-12 at 00 07 39" src="https://user-images.githubusercontent.com/6196452/38643366-912ce7e8-3de5-11e8-86d8-66549c17fbc5.png">

**Comment by mkalinin** [comment]
The value is correct. But `Memory used` from some point of view refers to _Memory used by Harmony instance_ not by entire OS. In your case I would think that Harmony uses `15.88 GB` which is weird

**Comment by zilm13** [comment]
<img width="176" alt="screen shot 2018-04-13 at 11 20 55" src="https://user-images.githubusercontent.com/6196452/38724679-a07b62e6-3f0d-11e8-98f1-77dcf9077a14.png">

What do you think about this? Free space is not clear in numbers what I don't like but visible. I don't see a way to add it while keeping panel without a mess.

**Comment by zilm13** [comment]
Should be resolved with https://github.com/ether-camp/ethereum-harmony/commit/fbf98b807b2b61fca4c6f7ed4890b0cf7722b97f and https://github.com/ether-camp/ethereum-harmony/commit/c0612b0eaa2981e2059ab628d94f3536c60f4d1f
