### ISSUE TITLE
problem with unknown error 

### ISSUE THREAD

**Issue by 3Mohammed2013** [ether-camp/ethereum-harmony#78]
> Task :compileJava 
/home/rootf/ethereum-harmony/src/main/java/com/ethercamp/harmony/service/ContractsService.java:154: error: method init in interface DbSource<V> cannot be applied to given types;
        contractsStorage.init();
                        ^
  required: DbSettings
  found: no arguments
  reason: actual and formal argument lists differ in length
  where V is a type-variable:
    V extends Object declared in interface DbSource
/home/rootf/ethereum-harmony/src/main/java/com/ethercamp/harmony/service/ContractsService.java:157: error: method init in interface DbSource<V> cannot be applied to given types;
        settingsStorage.init();
                       ^
  required: DbSettings
  found: no arguments
  reason: actual and formal argument lists differ in length
  where V is a type-variable:
    V extends Object declared in interface DbSource
/home/rootf/ethereum-harmony/src/main/java/com/ethercamp/harmony/service/ContractsService.java:160: error: method init in interface DbSource<V> cannot be applied to given types;
        contractCreation.init();
                        ^
  required: DbSettings
  found: no arguments
  reason: actual and formal argument lists differ in length
  where V is a type-variable:
    V extends Object declared in interface DbSource
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed

**Comment by zilm13** [comment]
@3Mohammed2013 Fixed, thank you for feedback!
You may need to clean you cache to make fix available (ethereumj dependency should be redownloaded by gradle)

**Comment by 3Mohammed2013** [comment]
./gradlew cleanBuildCache  I was use this comment but it not works probably ,

**Comment by 3Mohammed2013** [comment]
i was use those comment which it same like this comment  "rm -rf $HOME/.gradle/caches/"
cd ~/.gradle
rm -rf caches/

it works know really thanks 
i have question can i implemented the access control in harmony

**Comment by zilm13** [comment]
@3Mohammed2013 
> i have question can i implemented the access control in harmony
We want this as feature, but not yet ready, even started.
I guess the simplest way is to put Harmony behind proxy, such as nginx and use simple htaccess

**Comment by zilm13** [comment]
@3Mohammed2013 Made an issue https://github.com/ether-camp/ethereum-harmony/issues/79 not to forget. But I cannot give any schedule estimate for it.
