### ISSUE TITLE
Compile failed when pull the last version 

### ISSUE THREAD

**Issue by majingfenggithub** [ether-camp/ethereum-harmony#84]
D:\project\01_code\ethereum-harmony\src\main\java\com\ethercamp\harmony\service\BlockchainInfoService.java:31: 错误: 找不到符号
import org.ethereum.listener.RecommendedGasPriceTracker;
                            ^
  符号:   类 RecommendedGasPriceTracker
  位置: 程序包 org.ethereum.listener
D:\project\01_code\ethereum-harmony\src\main\java\com\ethercamp\harmony\service\BlockchainInfoService.java:137: 错误: 找不到符号
    class GasPriceTracker extends RecommendedGasPriceTracker {
                                  ^
  符号:   类 RecommendedGasPriceTracker
  位置: 类 BlockchainInfoService
2 个错误
:compileJava FAILED

This file is update by list: 

Replay last blocks for accurate recommended gas price at start Dmitry Shmatko 2018/4/19 7:14
Recommended gas price algorithm improved, output made more clear Dmitry Shmatko 2018/4/19 2:35

**Comment by mkalinin** [comment]
did you try to clean gradle cache? if not it worth to be tried

**Comment by majingfenggithub** [comment]
It's my mistake. I have clean the cache and now it's ok
