### ISSUE TITLE
Unknown command-line option '-X'.

### ISSUE THREAD

**Issue by Moha66** [ether-camp/ethereum-harmony#86]
Hi
I tryied to run this line 

./gradlew runPrivate -Xmx3500M -Dethereumj.conf.res=private.conf -Ddatabase.name=database-private -Dmine.fullDataSet=true

The output would be
* What went wrong:
Problem configuring task :runPrivate from command line.
> Unknown command-line option '-X'.

Could anyone please help me.
Thank you.

**Comment by mkalinin** [comment]
for JVM options please use `-PjvmArgs="-Xmx3500M"`

**Comment by Moha66** [comment]
Thank you very much it works 

./gradlew runPrivate -PjvmArgs -Dethereumj.conf.res=private.conf -Ddatabase.name=database-private -Dmine.fullDataSet=true

**Comment by mkalinin** [comment]
not at all 👍
