### ISSUE TITLE
Update eth_getTransactionReceipt interface

### ISSUE THREAD

**Issue by mkalinin** [ether-camp/ethereum-harmony#92]
[This](https://github.com/ethereum/wiki/wiki/JSON-RPC/_compare/ea47c31b36b00415fe5b54db36ddad43c9bf650e...9a44e423b2ebe77580f9e5d7c393164acf6c03ae) change introduces `from` and `to` parameters into `eth_getTransactionReceipt` method. Need to check whether they are supported by Harmony

**Comment by zilm13** [comment]
Resolved with https://github.com/ether-camp/ethereum-harmony/commit/011c6e1e5c00f979caedfa849da077eb7b234b4c
